resources:
  - name: artifact_info
    type: IncomingWebhook
    configuration:
      webhookName: curate_artifact 
pipelines:
 - name: curate_artifact
   steps:
   - name: sendNotification
     type: Bash
     configuration:
      inputResources:
        - name: artifact_info
          trigger: true
      integrations:
        - name: ArtifactorySaaS
     execution:
             #      onStart:
             #          - set -x
      onExecute:
        - POM=`echo $res_artifact_info_payload | jq -r -c '.name'` 
        - >-
          retry_command jfrog rt config --url $int_ArtifactorySaaS_url --user
          $int_ArtifactorySaaS_user --apikey $int_ArtifactorySaaS_apikey
          --interactive=false
        - echo "send_notification shimiNotify \"received request to clear $POM \""
        - jfrog rt curl /maven-wellsfargo-demo-remote/${POM} 
        - echo "{\"componentID\":\"gav://com.fasterxml.jackson.core:jackson-databind:2.11.0\"}" > f.json
        - curl -H "Content-Type:application/json" -u$int_ArtifactorySaaS_user:$int_ArtifactorySaaS_apikey -XPOST --data @f.json "https://soleng.jfrog.io/xray/api/v1/scanArtifact"
        - sleep 5
        - echo "{\"components_id\":[\"gav://com.fasterxml.jackson.core:jackson-databind:2.11.0\"]}" > f2.json
        - curl -H "Content-Type:application/json" -u$int_ArtifactorySaaS_user:$int_ArtifactorySaaS_apikey -XPOST --data @f2.json "https://soleng.jfrog.io/xray/api/v1/component/searchCvesByComponents"
        - jfrog rt cp "/maven-wellsfargo-demo-remote/${POM}" maven-wellsfargo-demo-cleared-local/
