apiVersion: v1.1
resources:
  - name: release_bundle_acme
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb_acme
      version: v1.0.0
  - name: signed_bundle_acme
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb_acme
      version: v1.0.0
  - name: distribution_rules_acme
    type: DistributionRule
    configuration:
      sourceDistribution: Distribution
      serviceName: Edge*
      siteName: Edge*
      cityName: '*'
      countryCodes:
        - '*'
pipelines:      
- name: ACME_release_mgmt
#  configuration:
        #          nodePool: Ubuntu
  steps:
  - name: bundle
    type: CreateReleaseBundle
    configuration:
      releaseBundleName: demo_rb_acme
      releaseBundleVersion: 'v1.0.${run_number}'
      dryRun: false
      sign: false
      description: some random test description
      inputResources:
        - name: gosvc_promoted_build_info
          trigger: false
        - name: appl_promoted_build_info_acme
          trigger: false
          #        - name: jenkins_job_build_info
          # trigger: false
      outputResources:
        - name: release_bundle_acme
      releaseNotes:
        syntax: markdown
        content: |
          ## Heading
            * Bullet
            * Points
  - name: sign
    type: SignReleaseBundle
    configuration:
      inputResources:
        - name: release_bundle_acme
      outputResources:
        - name: signed_bundle_acme
  - name: distribute
    type: DistributeReleaseBundle
    configuration:
      dryRun: false
      inputResources:
        - name: signed_bundle_acme
        - name: distribution_rules_acme
