resources:
  - name: artifact_arrived
    type: IncomingWebhook
    configuration:
      webhookName: artifact_to_scan
pipelines:
 - name: scan_artifact
   steps:
   - name: sendNotification
     type: Bash
     configuration:
      inputResources:
        - name: artifact_arrived
          trigger: true
     execution:
      onStart:
        - echo "send_notification shimiNotify \"artifact has arrived\""
   - name: download_jar_in_secluded_repo
     type: Bash
     configuration:
             inputSteps:
                     - name: sendNotification
     execution:
      onStart:
        - POM=echo $res_artifact_arrived_payload | jq -c '.data.path' 
        - JAR="${POM%.pom}.jar"
        - jfrog rt curl -XHEAD /quar_maven/${JAR}


     
