resources:
  - name: artifact_arrived
    type: IncomingWebhook
    configuration:
      webhookName: artifact_to_scan
pipelines:
 - name: scan_artifact
   steps:
   - name: sendNotification
     type: Bash
     configuration:
      inputResources:
        - name: artifact_arrived
          trigger: true
     execution:
      onStart:
        - echo "send_notification shimiNotify \"artifact has arrived\""
        - echo "$res_artifact_arrived_payload"
        - POM=`echo $res_artifact_arrived_payload | jq -c '.data.path'` 
        - echo "$POM"
        - JAR="${POM%.pom}.jar"
        - echo "$JAR"
        - jfrog rt curl -XHEAD /quar_maven/${JAR}


     
